name: Cypress Automation

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI
    inputs:
      file_name:
        description: 'Specify the test file name (e.g., Test1.js)'
        required: true
        default: 'Test1.js'     

  push: # Automatically triggers on pushes to the repository
    branches:
      - main # Replace with your branch name if different

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the version compatible with Cypress

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Cypress Binary
      - name: Install Cypress
        run: npx cypress install

      # Step 5: Run the specific Cypress test
      - name: Run Specific Cypress Test
        run: npx cypress run --spec cypress/e2e/Tests/${{ github.event.inputs.file_name }}

      - name: Save Cypress artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results/

